# Generated by Django 5.0.6 on 2024-07-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('AutCod', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('AutVer', models.CharField(max_length=255)),
                ('AutFecIng', models.DateField()),
                ('AutAli', models.CharField(max_length=255)),
                ('AutCom', models.CharField(max_length=255)),
                ('AutApeMat', models.CharField(max_length=255)),
                ('AutApePat', models.CharField(max_length=255)),
                ('AutNom', models.CharField(max_length=255)),
                ('AutCon', models.CharField(max_length=255)),
                ('AutTel', models.CharField(max_length=255)),
                ('AutDNI', models.CharField(max_length=255)),
                ('AutOrgCod_id', models.CharField(max_length=255)),
                ('AutEstCod_id', models.CharField(max_length=255)),
            ],
        ),
    ]
