# Generated by Django 5.0.6 on 2024-07-18 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleActor',
            fields=[
                ('RolActCod', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('RolActNom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('EstCod', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('EstNom', models.CharField(max_length=255, verbose_name='Nombre')),
                ('EstDescrip', models.CharField(max_length=255, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='TypeActor',
            fields=[
                ('TipActCod', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('TipActNomAct', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('AutCod', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('AutVer', models.FloatField()),
                ('AutFecIng', models.DateField()),
                ('AutAli', models.CharField(max_length=255)),
                ('AutCom', models.CharField(max_length=255)),
                ('AutApeMat', models.CharField(max_length=255)),
                ('AutApePat', models.CharField(max_length=255)),
                ('AutNom', models.CharField(max_length=255)),
                ('AutCon', models.CharField(max_length=255)),
                ('AutTel', models.IntegerField()),
                ('AutDNI', models.IntegerField()),
                ('AutOrgCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('AutEstCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.state')),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('ActCod', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ActVer', models.FloatField()),
                ('ActFecCrea', models.DateField(auto_now_add=True)),
                ('ActFecMod', models.DateField()),
                ('ActCom', models.CharField(max_length=255)),
                ('ActArtCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.artifact')),
                ('ActProCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto')),
                ('ActAutPlaCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autores_placod', to='usuario.author')),
                ('ActRolActCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.roleactor')),
                ('ActEstCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.state')),
                ('ActTipActCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.typeactor')),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('ExpCod', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ExpVer', models.FloatField()),
                ('ExpFecCre', models.DateField(auto_now_add=True)),
                ('ExpFecMod', models.DateField()),
                ('ExpApePat', models.CharField(max_length=255)),
                ('ExpApeMat', models.CharField(max_length=255)),
                ('ExpNom', models.CharField(max_length=255)),
                ('ExpExp', models.CharField(max_length=255)),
                ('ExpCom', models.CharField(max_length=255)),
                ('ExpArtCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.artifact')),
                ('ExpAutPlaCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experto_autor_plan', to='usuario.author')),
                ('ExpProCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto')),
                ('ExpEstaCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.state')),
            ],
        ),
        migrations.CreateModel(
            name='Font',
            fields=[
                ('FueCod', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('FueVer', models.FloatField()),
                ('FueFecCre', models.DateField(auto_now_add=True)),
                ('FueFecMod', models.DateField()),
                ('FueCom', models.CharField(max_length=255)),
                ('FueAutPlanCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuente_autor_plan', to='usuario.author')),
                ('FueProCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto')),
                ('FueEstCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.state')),
            ],
        ),
        migrations.CreateModel(
            name='ModificationArtifact',
            fields=[
                ('ModArtCod', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ModArtFecMod', models.DateField()),
                ('ModArtCom', models.CharField(max_length=255)),
                ('ModArtTipPlan', models.CharField(max_length=255)),
                ('ModArtVer', models.FloatField()),
                ('ModArtArtCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.artifact')),
                ('ModArtAutCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.author')),
            ],
        ),
        migrations.CreateModel(
            name='OperationArtifact',
            fields=[
                ('OpeArtCod', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('OpeArtNom', models.CharField(max_length=255)),
                ('OperArtArtCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.artifact')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorPermission',
            fields=[
                ('PerAutCod', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('PerAutAutCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.author')),
                ('PerAutOpeArtCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.operationartifact')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('RepCod', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('RepFec', models.DateField()),
                ('RepProCod', models.CharField(max_length=255)),
                ('RepVer', models.FloatField()),
                ('RepFil', models.FileField(upload_to='reports/')),
                ('RepArtCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.artifact')),
                ('RepAutCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.author')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('RolCod', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('RolNom', models.CharField(max_length=255)),
                ('RolFecCre', models.DateField(auto_now_add=True)),
                ('RolCom', models.CharField(max_length=255)),
                ('RolOrgCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorRole',
            fields=[
                ('AutRolCod', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('AutRolAutCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.author')),
                ('AutRolRolCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.role')),
            ],
        ),
        migrations.CreateModel(
            name='Educcion',
            fields=[
                ('EduCod', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('EduVer', models.FloatField()),
                ('EduFecCre', models.DateField(auto_now_add=True)),
                ('EduFecMod', models.DateField()),
                ('EduCom', models.CharField(max_length=255)),
                ('EduActCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.actor')),
                ('EduArtCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.artifact')),
                ('EduAutCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.author')),
                ('EduProCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto')),
                ('EduExpCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.expert')),
                ('EduFueCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.font')),
                ('EduEstCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.state')),
            ],
        ),
    ]
