# Generated by Django 5.0.6 on 2024-07-23 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_rename_atnom_artifact_artnom'),
        ('proyecto', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('EntrCod', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('EntrVer', models.FloatField()),
                ('EntrFecCre', models.DateField(auto_now_add=True)),
                ('EntrFecMod', models.DateField()),
                ('EntrNomPer', models.CharField(max_length=50)),
                ('EntrCargPer', models.CharField(max_length=50)),
                ('EntrCom', models.CharField(max_length=255)),
                ('EntrActCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.actor')),
                ('EntrArtCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.artifact')),
                ('EntrAutCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.author')),
                ('EntrEstCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.state')),
                ('EntrExpCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.expert')),
                ('EntrFueCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.font')),
                ('EntrProCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto')),
            ],
        ),
    ]
