# Generated by Django 5.0.6 on 2024-07-23 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_rename_atnom_artifact_artnom'),
        ('proyecto', '0001_initial'),
        ('usuario', '0002_entrevista'),
    ]

    operations = [
        migrations.AddField(
            model_name='educcion',
            name='EduNom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='educcion',
            name='EduActCod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.actor'),
        ),
        migrations.AlterField(
            model_name='educcion',
            name='EduArtCod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.artifact'),
        ),
        migrations.AlterField(
            model_name='educcion',
            name='EduAutCod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.author'),
        ),
        migrations.AlterField(
            model_name='educcion',
            name='EduFueCod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.font'),
        ),
        migrations.CreateModel(
            name='Ilacion',
            fields=[
                ('IlaCod', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('IlaNom', models.CharField(blank=True, max_length=50, null=True)),
                ('IlaVer', models.IntegerField()),
                ('IlaFecCre', models.DateField(auto_now_add=True)),
                ('IlaFecMod', models.DateField()),
                ('IlaCom', models.CharField(blank=True, max_length=255)),
                ('IlaActCod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.actor')),
                ('IlaArtCod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.artifact')),
                ('IlaAutPlanCod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.author')),
                ('IlaEduCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.educcion')),
                ('IlaEstCod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.state')),
                ('IlaExpCod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.expert')),
                ('IlaFueCod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.font')),
                ('IlaProCod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyecto.proyecto')),
            ],
        ),
    ]
