# Generated by Django 5.0.6 on 2024-07-23 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_educcion_edunom_alter_educcion_eduactcod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilacion',
            name='IlaEduCod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilaciones', to='usuario.educcion'),
        ),
    ]
