# Generated by Django 5.0.6 on 2024-07-24 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_rename_atnom_artifact_artnom'),
        ('proyecto', '0001_initial'),
        ('usuario', '0004_alter_ilacion_ilaeducod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especificacion',
            fields=[
                ('EspCod', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('EspNom', models.CharField(blank=True, max_length=50, null=True)),
                ('EspVer', models.FloatField()),
                ('EspFecCre', models.DateField(auto_now_add=True)),
                ('EspFecMod', models.DateField()),
                ('EspCom', models.CharField(blank=True, max_length=255)),
                ('EspActCod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.actor')),
                ('EspArtCod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.artifact')),
                ('EspAutPlanCod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.author')),
                ('EspEstCod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.state')),
                ('EspExpCod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.expert')),
                ('EspFueCod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.font')),
                ('EspIlaCod', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='especificacion', to='usuario.ilacion')),
                ('EspProCod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyecto.proyecto')),
            ],
        ),
    ]
