# Generated by Django 5.0.6 on 2024-07-18 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryEvidence',
            fields=[
                ('CatEviCod', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('CatEviNom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Conclusion',
            fields=[
                ('ConCod', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ConTex', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('AgeCod', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('AgeTex', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('EviCod', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('EviNom', models.CharField(max_length=255)),
                ('EviFec', models.DateField()),
                ('EviArc', models.FileField(upload_to='evidences/')),
                ('EviArtCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.artifact')),
                ('EviCatEviCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.categoryevidence')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('EntCod', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('EntVer', models.FloatField()),
                ('EntFec', models.DateField()),
                ('EntNomEnt', models.CharField(max_length=255)),
                ('EntCarEnt', models.CharField(max_length=255)),
                ('EntHorIni', models.TimeField()),
                ('EntHorFin', models.TimeField()),
                ('EntDur', models.IntegerField()),
                ('EntObsTie', models.CharField(max_length=255)),
                ('EntObs', models.TextField()),
                ('EntArtCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.artifact')),
            ],
        ),
    ]
