# Generated by Django 5.0.6 on 2024-07-18 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '0001_initial'),
        ('proyecto', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='EntAutCod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.author'),
        ),
        migrations.AddField(
            model_name='interview',
            name='EntProCod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='EviEntCod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.interview'),
        ),
        migrations.AddField(
            model_name='conclusion',
            name='ConEntCod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.interview'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='AgeEntCod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.interview'),
        ),
    ]
